#!/bin/tcsh
~/Documents/webpage/classPageAutoGenerator/generate index.txt syllabus.txt classExamples.txt homework.txt basicUnix.txt software.txt
scp -r ../cs112Spring12/ pedcs@helios.hampshire.edu:~/public_html/classes/
