#!/bin/bash

MAX=26

# grab hw number
hw=`echo $1 | sed "s/^[^1-9]*\([1-9][0-9]*\).*$/\1/"`

# reject a missing number
if [  -z "$hw" ]; then
    echo "Could not find homework number"
fi

# reject numbers that are out of the range
if [ $hw -gt 26 ] || [ $hw -lt 1 ]; then
    echo "Homework number should be between 1 and 26"
    exit 1
fi

hw=hw`printf "%02d" $hw`

if [ "$hw" != "$1" ]; then
    echo "Assuming you meant $hw"
fi

git add .
git commit -m "$1 done"
git tag --force $1
git push
git push --tags
